import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

import { cn } from '@/lib/utils';

import SessionAuthProvider from '@/context/SessionAuthProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('inter.classname min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <main>
          <SessionAuthProvider>
            <main>{children}</main>
          </SessionAuthProvider>
        </main>
      </body>
    </html>
  );
}
