version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: backend/api-shifts/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./backend/api-shifts:/src/backend/api-shifts
    depends_on:
      - db
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  external:
    build:
      context: ./external-api
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - api

  socketserver:
    build:
      context: ./socketServer
      dockerfile: Dockerfile
    ports:
      - "3002:3002"  # Ajusta el puerto según tu configuración
    networks:
      - app-network
    depends_on:
      - api
  

volumes:
  db_data:

networks:
  app-network: